# Generated by Django 3.1.2 on 2020-11-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_xml',
            name='file_xml',
            field=models.FileField(default=None, upload_to='xml_stored/'),
            preserve_default=False,
        ),
    ]
