# Generated by Django 3.1.2 on 2020-11-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_add_xml_file_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_xml',
            name='ruta_xml',
        ),
    ]
